Define env vars via CLI

diff --git a/bin/buildkite-trigger b/bin/buildkite-trigger
--- a/bin/buildkite-trigger
+++ b/bin/buildkite-trigger
@@ -15,6 +15,7 @@ MESSAGE="Triggered from script"
 
 # === Derived values ===
 REPOS=()
+ENVS=()
 DRY_RUN=false
 FORCE=false
 
@@ -40,6 +41,10 @@ while [[ $# -gt 0 ]]; do
 	case "$1" in
 	-r | --repo)
 		REPOS+=("$2")
+		shift 2
+		;;
+	-E | --env)
+		ENVS+=("$2")
 		shift 2
 		;;
 	-n | --dry-run)
@@ -74,6 +79,17 @@ if [[ -z "${PIPELINE:-}" ]]; then
 	exit 1
 fi
 
+# Check for valid env syntax before we move on
+# Basically VAR=.*
+envs_ok=true
+for env in "${ENVS[@]}"; do
+	if [[ ! "$env" =~ ^[^[:space:]=]+=.*$ ]]; then
+		echo "Error: invalid environment variable definition '$env'" >&2
+		envs_ok=false
+	fi
+done
+$envs_ok || exit 1
+
 # === Collect env vars ===
 declare -A env_map
 
@@ -90,6 +106,13 @@ for repo_path in "${REPOS[@]}"; do
 		log::error "$repo_path is not a valid Git repository"
 		((out_of_sync += 1))
 	fi
+done
+
+# Add the command line definitions.
+for env in "${ENVS[@]}"; do
+	key=${env%%=*}
+	val=${env#*=}
+	env_map["$key"]="$val"
 done
 
 if [[ "$FORCE" == false && "$out_of_sync" -gt 0 ]]; then
